(()=>{
'use strict';
const $=id=>document.getElementById(id);
const STORAGE='inj_node_futures_positions_v1';
const ACTIVE='inj_node_futures_active_v1';
const SPOT_STORAGE='inj_node_futures_spot_inj_v1';
const LANG=()=>{try{return localStorage.getItem('inj_node_language_v1')==='en'?'en':'it'}catch(_){return'it'}};
const state={side:'long',price:0,lastPrice:0,source:'KuCoin',positions:[],activeId:'',timer:null,eur:1,spot:0,spotStored:false};
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=(v,d=4)=>Number.isFinite(v)?v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const money=(v)=>{const eur=localStorage.getItem('inj_monitor_currency')==='EUR';const amount=eur?v*state.eur:v;return `${v>=0?'+':'-'}${eur?'€':'$'}${Math.abs(amount).toLocaleString(eur?'it-IT':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`.replace(`${eur?'€':'$'}-`,`${eur?'€':'$'}`)};
function read(){try{state.positions=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(!Array.isArray(state.positions))state.positions=[]}catch(_){state.positions=[]}try{state.activeId=localStorage.getItem(ACTIVE)||''}catch(_){}try{const raw=localStorage.getItem(SPOT_STORAGE);state.spotStored=raw!==null&&raw!=='';state.spot=Math.max(0,n(raw))}catch(_){state.spot=0;state.spotStored=false} }
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state.positions));localStorage.setItem(ACTIVE,state.activeId||'')}catch(_){} }
function current(){return state.positions.find(p=>p.id===state.activeId)||null}
function draft(){return {side:state.side,entry:n($('entryInput')?.value),leverage:Math.max(1,n($('leverageInput')?.value)||1),margin:n($('marginInput')?.value),mode:$('marginModeInput')?.value||'isolated',liq:n($('liquidationInput')?.value),name:($('nameInput')?.value||'').trim()}}
function estimatedLiq(p){if(p.liq>0)return p.liq;if(p.mode==='cross')return 0;if(!(p.entry>0&&p.leverage>0))return 0;const raw=p.side==='long'?p.entry*(1-1/p.leverage):p.entry*(1+1/p.leverage);return Math.max(0,raw)}
function calc(p){const price=state.price,entry=p.entry,lev=p.leverage,margin=p.margin;if(!(price>0&&entry>0&&lev>0&&margin>0))return null;const size=margin*lev,qty=size/entry,dir=p.side==='short'?-1:1,pnl=qty*(price-entry)*dir,roi=pnl/margin*100,move=(price/entry-1)*100,liq=estimatedLiq(p),liqDist=liq>0?Math.abs(price-liq)/price*100:0;return{price,size,qty,pnl,roi,move,liq,liqDist}}
function renderPortfolio(){const list=state.positions||[];let invested=0,pnl=0;list.forEach(p=>{const margin=Math.max(0,n(p.margin));invested+=margin;const c=calc(p);if(c)pnl+=c.pnl});const equity=invested+pnl,roi=invested>0?pnl/invested*100:0,futuresInj=state.price>0?Math.max(0,equity)/state.price:0,spot=Math.max(0,state.spot||0),spotValue=state.price>0?spot*state.price:0,totalInj=spot+futuresInj,totalValue=state.price>0?totalInj*state.price:0;const eur=localStorage.getItem('inj_monitor_currency')==='EUR';const rate=eur?state.eur:1;const plain=v=>`${eur?'€':'$'}${Math.abs(v*rate).toLocaleString(eur?'it-IT':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;if($('portfolioInvested'))$('portfolioInvested').textContent=list.length?plain(invested):'—';if($('portfolioPnl')){$('portfolioPnl').textContent=list.length&&state.price>0?`${pnl>0?'+':pnl<0?'−':''}${plain(pnl)}`:'—';$('portfolioPnl').className=pnl>0?'positive':pnl<0?'negative':'neutral'}if($('portfolioRoi'))$('portfolioRoi').textContent=list.length&&state.price>0?`ROI ${roi>0?'+':''}${roi.toFixed(2)}%`:'ROI —';if($('portfolioEquity'))$('portfolioEquity').textContent=list.length&&state.price>0?plain(equity):'—';if($('portfolioInj'))$('portfolioInj').textContent=list.length&&state.price>0?`${futuresInj.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:3})} INJ`:'—';if($('portfolioCount'))$('portfolioCount').textContent=`${list.length} ${LANG()==='en'?(list.length===1?'position':'positions'):(list.length===1?'posizione':'posizioni')}`;if($('spotValue'))$('spotValue').textContent=state.spotStored&&state.price>0?plain(spotValue):'—';if($('futuresCloseInj'))$('futuresCloseInj').textContent=list.length&&state.price>0?`${futuresInj.toLocaleString('en-US',{minimumFractionDigits:3,maximumFractionDigits:4})} INJ`:'—';if($('totalCloseInj'))$('totalCloseInj').textContent=state.price>0&&(state.spotStored||list.length)?`${totalInj.toLocaleString('en-US',{minimumFractionDigits:3,maximumFractionDigits:4})} INJ`:'—';if($('totalCloseValue'))$('totalCloseValue').textContent=state.price>0&&(state.spotStored||list.length)?`${plain(totalValue)} · Spot + Futures`:'—'}
function setSide(side){state.side=side==='short'?'short':'long';document.querySelectorAll('[data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===state.side));render()}
function formToCurrent(){const p=draft();const card=$('positionCard');const c=calc(p);card.classList.remove('profit','loss');if(c){card.classList.add(c.pnl>0?'profit':c.pnl<0?'loss':'');$('pnlValue').textContent=money(c.pnl);$('pnlPercent').textContent=`ROI ${c.roi>=0?'+':''}${c.roi.toFixed(2)}%`; $('entryMetric').textContent=`$${fmt(p.entry,4)}`;$('priceMetric').textContent=`$${fmt(c.price,4)}`;$('leverageMetric').textContent=`${p.leverage.toFixed(p.leverage%1?1:0)}×`;$('marginMetric').textContent=`$${fmt(p.margin,2)}`;$('sizeMetric').textContent=`$${fmt(c.size,2)}`;$('moveMetric').textContent=`${c.move>=0?'+':''}${c.move.toFixed(2)}%`;$('quantityValue').textContent=`${fmt(c.qty,3)} INJ`;$('liqDistance').textContent=`${c.liqDist.toFixed(2)}%`;$('liqValue').textContent=c.liq?`$${fmt(c.liq,4)}`:'—';$('rangeEntry').textContent=`$${fmt(p.entry,4)}`;$('rangeLive').textContent=`$${fmt(c.price,4)}`;$('liqMeta').textContent=p.liq>0?(LANG()==='en'?'KuCoin value entered manually':'Valore KuCoin inserito manualmente'):(LANG()==='en'?'Indicative estimate · fees/funding excluded':'Stima indicativa · commissioni/funding esclusi');$('positionNote').textContent=p.mode==='cross'?(LANG()==='en'?'Cross margin: liquidation cannot be estimated precisely without account equity and KuCoin risk tier.':'Cross margin: la liquidazione non è stimabile con precisione senza equity account e risk tier KuCoin.'):(LANG()==='en'?'Isolated position monitor · P/L excludes fees and funding.':'Monitor posizione Isolated · P/L al netto di fee/funding non incluso.');renderRange(p,c)}else{$('pnlValue').textContent='—';$('pnlPercent').textContent='ROI —';['entryMetric','priceMetric','leverageMetric','marginMetric','sizeMetric','moveMetric','quantityValue','liqDistance','liqValue','rangeEntry','rangeLive'].forEach(id=>$(id).textContent='—');$('positionNote').textContent=LANG()==='en'?'Enter position data to start.':'Inserisci i dati della posizione per iniziare.'}}
function renderRange(p,c){const vals=[c.liq,p.entry,c.price].filter(v=>v>0);if(vals.length<2)return;let min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const pad=span*.22;min=Math.max(0,min-pad);max+=pad;span=max-min||1;const pos=v=>Math.max(0,Math.min(100,(v-min)/span*100));$('liqMarker').style.left=`${pos(c.liq)}%`;$('entryMarker').style.left=`${pos(p.entry)}%`;$('liveMarker').style.left=`${pos(c.price)}%`;const a=Math.min(pos(c.liq),pos(c.price)),b=Math.max(pos(c.liq),pos(c.price));$('rangeFill').style.left=`${a}%`;$('rangeFill').style.width=`${Math.max(1,b-a)}%`}
function renderSaved(){const host=$('savedList');$('savedCount').textContent=String(state.positions.length);if(!state.positions.length){host.innerHTML='<div class="empty-state">Nessuna posizione salvata.</div>';return}host.innerHTML=state.positions.map(p=>{const c=calc(p);const pnl=c?`${c.roi>=0?'+':''}${c.roi.toFixed(1)}%`:'—';return `<article class="saved-position ${p.id===state.activeId?'active':''}" data-id="${p.id}"><div class="saved-row"><strong>${escapeHtml(p.name||`INJ ${p.side.toUpperCase()} ${p.leverage}x`)}</strong><span class="side ${p.side}">${p.side.toUpperCase()}</span></div><small>Entry $${fmt(p.entry,4)} · ${p.leverage}× · ${p.mode==='cross'?'Cross':'Isolated'} · ROI ${pnl}</small><button type="button" class="delete-position" data-delete="${p.id}">Elimina</button></article>`}).join('');host.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('[data-delete]'))return;loadPosition(el.dataset.id)}));host.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();removePosition(btn.dataset.delete)}))}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function loadPosition(id){const p=state.positions.find(x=>x.id===id);if(!p)return;state.activeId=id;state.side=p.side;setSide(p.side);$('entryInput').value=p.entry||'';$('leverageInput').value=p.leverage||'';$('marginInput').value=p.margin||'';$('marginModeInput').value=p.mode||'isolated';$('liquidationInput').value=p.liq||'';$('nameInput').value=p.name||'';save();render()}
function removePosition(id){state.positions=state.positions.filter(p=>p.id!==id);if(state.activeId===id)state.activeId=state.positions[0]?.id||'';save();if(state.activeId)loadPosition(state.activeId);else clearForm();renderSaved()}
function clearForm(){state.activeId='';state.side='long';$('entryInput').value='';$('leverageInput').value='';$('marginInput').value='';$('marginModeInput').value='isolated';$('liquidationInput').value='';$('nameInput').value='';setSide('long');save();render()}
function persistForm(){const p=draft();if(!(p.entry>0&&p.leverage>0&&p.margin>0))return;const existing=current();const item={...p,id:existing?.id||`f_${Date.now().toString(36)}`,updated:Date.now()};const idx=state.positions.findIndex(x=>x.id===item.id);if(idx>=0)state.positions[idx]=item;else state.positions.unshift(item);state.activeId=item.id;save();renderSaved();render()}
async function fetchPrice(){let price=0,source='KuCoin';try{const r=await fetch('https://api-futures.kucoin.com/api/v1/ticker?symbol=INJUSDTM',{cache:'no-store'});if(r.ok){const j=await r.json();price=n(j?.data?.price)}}catch(_){}if(!(price>0)){source='Fallback';try{const r=await fetch('https://api.binance.com/api/v3/ticker/price?symbol=INJUSDT',{cache:'no-store'});if(r.ok){const j=await r.json();price=n(j?.price)}}catch(_){}}if(price>0){state.lastPrice=state.price;state.price=price;state.source=source;$('liveBadge').classList.remove('off');$('livePrice').textContent=`$${fmt(price,4)}`;$('sourceValue').textContent=source==='KuCoin'?'KuCoin Futures':'Fallback market';$('updatedValue').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});render()}else{$('liveBadge').classList.add('off');$('updatedValue').textContent=LANG()==='en'?'Market feed unavailable':'Feed mercato non disponibile'}}
async function loadEur(){try{const cached=n(localStorage.getItem('inj_monitor_eur_rate'));if(cached>0)state.eur=cached}catch(_){} }
function render(){formToCurrent();renderSaved();renderPortfolio()}
function bind(){document.querySelectorAll('[data-side]').forEach(b=>b.addEventListener('click',()=>setSide(b.dataset.side)));['entryInput','leverageInput','marginInput','marginModeInput','liquidationInput','nameInput'].forEach(id=>$(id).addEventListener('input',render));const spotInput=$('spotInjInput');if(spotInput){spotInput.value=state.spotStored?String(state.spot):'';spotInput.addEventListener('input',()=>{state.spot=Math.max(0,n(spotInput.value));state.spotStored=spotInput.value!=='';try{if(state.spotStored)localStorage.setItem(SPOT_STORAGE,String(state.spot));else localStorage.removeItem(SPOT_STORAGE)}catch(_){}renderPortfolio()})}$('positionForm').addEventListener('submit',e=>{e.preventDefault();persistForm()});$('clearButton').addEventListener('click',clearForm);$('newPositionButton').addEventListener('click',clearForm);$('futuresHome').addEventListener('click',e=>{e.preventDefault();try{sessionStorage.setItem('inj_node_return_home','1')}catch(_){}let back=false;try{const ref=document.referrer?new URL(document.referrer):null;back=!!(ref&&ref.origin===location.origin&&(ref.pathname.endsWith('/index.html')||ref.pathname.endsWith('/'))&&history.length>1)}catch(_){}if(back)history.back();else location.replace('./index.html')});window.addEventListener('storage',e=>{if(e.key==='inj_monitor_theme')document.documentElement.dataset.theme=localStorage.getItem('inj_monitor_theme')||'navy';if(e.key==='inj_monitor_currency')render();if(e.key===SPOT_STORAGE){const raw=localStorage.getItem(SPOT_STORAGE);state.spotStored=raw!==null&&raw!=='';state.spot=Math.max(0,n(raw));if($('spotInjInput'))$('spotInjInput').value=state.spotStored?String(state.spot):'';renderPortfolio()}})}
function init(){read();loadEur();bind();if(state.activeId&&state.positions.some(p=>p.id===state.activeId))loadPosition(state.activeId);else if(state.positions.length)loadPosition(state.positions[0].id);else render();fetchPrice();state.timer=setInterval(fetchPrice,2500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)fetchPrice()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
